# Generated by Django 6.0.4 on 2026-04-20 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('submitted_by', models.CharField(default='익명', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('agree', '동의'), ('disagree', '비동의')], max_length=10)),
                ('session_key', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='snacks.snack')),
            ],
            options={
                'unique_together': {('snack', 'session_key')},
            },
        ),
    ]
